### ISSUE TITLE
Create wireframe for frontend

### ISSUE THREAD

**Issue by olliesharp5** [douglas86/january-hackathon-team8#4]

**Comment by nikimacm** [comment]
![Add-bills](https://github.com/douglas86/january-hackathon-team8/assets/68541318/2dd68f0a-cd51-4cf4-9bf7-d9cee003840a)
![add-Expense](https://github.com/douglas86/january-hackathon-team8/assets/68541318/3c444c67-5544-4d4f-8edb-67c0bbe18973)
![Budget](https://github.com/douglas86/january-hackathon-team8/assets/68541318/c097bcf9-1e52-4c9f-bf26-2af34c604a3c)
![Dashboard](https://github.com/douglas86/january-hackathon-team8/assets/68541318/b782edae-4e3d-4e95-88bc-7fa1594238c5)
![Report](https://github.com/douglas86/january-hackathon-team8/assets/68541318/d5f9e116-0346-413a-8827-fb1b3c4d24b9)
![upcoming-bills](https://github.com/douglas86/january-hackathon-team8/assets/68541318/fbf13e18-e92d-438d-9cbf-de1ecf074b33)

**Comment by douglas86** [comment]
I am just writing some notes here:

- needing to create 4 app in django (dashboard, budget, reports, currency converter)

Dashboard app

- change status based on if it has been paid already
- status is reset on the first of every month

Database model

- Upcoming bills: title, due_date, status
- Expenses tracker: category, amount, date = this will be an auto_now parameter

Reports app

- Bar chart or Pie chart for the weekly or monthly reports

Budget app

Database model

- Expense: title, category, amount, date
