### ISSUE TITLE
BUG: Two logout links

### ISSUE THREAD

**Issue by douglas86** [douglas86/january-hackathon-team8#63]
I found this issue on header and it does shows 2 logout links when it was suppose to do show a logout button only once.

## Bug report

- The header shows 2 logout links
- There should only be one
- This is only when I log in

## Images of the Report

![Image](https://github.com/douglas86/january-hackathon-team8/assets/31186100/2304bf1e-b725-45e1-8681-d8585b6f6646)

**Comment by olliesharp5** [comment]
i can resolve this :)

**Comment by olliesharp5** [comment]
resolved, pull request created
